feat: 统一扫描器离线相关配置处理逻辑 #39
TencentBlueKing/ci-repoAnalysis pull request #40
Opened 2023-05-30 09:22 UTC by myqonnt

2023-05-30 10:17 UTC, cnlkl requested changes

2023-05-30 10:17 UTC, cnlkl commented on trivy/pkg/scan_executor.go
> +	if len(javaDbUrl) == 0 {
这边javaDbUrl不存在的时候为什么还要进入下载逻辑，这样从一个空字符串的url里下载是不是会失败

2023-05-30 10:17 UTC, cnlkl commented on trivy/pkg/scan_executor.go
> +	offline, err := config.GetBoolArg(constant.ConfigOffline)
这边`ConfigOffline`对应的配置不存在时一定会报错，会导致旧版本不兼容，可以判断一下这个配置不存在时就走原来的逻辑判断`url`配置是否存在

2023-05-30 10:41 UTC, myqonnt commented on trivy/pkg/scan_executor.go
> +	offline, err := config.GetBoolArg(constant.ConfigOffline)
offline, _ := config.GetBoolArg(constant.ConfigOffline)
offline = len(config.GetStringArg(constant.ArgDbDownloadUrl)) > 0
改成这样可以吗？

2023-05-30 10:42 UTC, myqonnt commented on trivy/pkg/scan_executor.go
> +	if len(javaDbUrl) == 0 {
不好意思，写错了，应该会 >

2023-05-30 10:51 UTC, myqonnt commented on trivy/pkg/scan_executor.go
> +	offline, err := config.GetBoolArg(constant.ConfigOffline)
```golang
offline, err := config.GetBoolArg(constant.ConfigOffline)
if err != nil {
    offline = len(config.GetStringArg(constant.ArgDbDownloadUrl)) > 0
}
```
改正这样可行吗？

2023-05-31 02:24 UTC, cnlkl approved these changes

2023-05-31 02:25 UTC, merged